name: Hourly ETL

on:
  schedule:
    - cron:  '0 * * * *'   # every hour
  workflow_dispatch:       # enables a manual “Run” button

jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: python -m crypto_etl.main
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'auto: append new price row'
