name: Hourly ETL

permissions:
  contents: write

on:
  push:                  # <-- This is the new part
    branches:            #
      - main             #
  schedule:
    - cron: '0 * * * *'      # hourly
  workflow_dispatch: {}

jobs:
  etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install -r requirements.txt

      - run: python -m crypto_etl.main           # update prices.csv & db
      # The next line is commented out because main.py already regenerates the chart
      # - run: python plot.py                   # generate docs/chart.png

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'auto: update data & chart'
