name: Hourly ETL

on:
  schedule:
    - cron: '0 * * * *'      # every hour at minute 0 (UTC)
  workflow_dispatch          # keeps the manual “Run workflow” button

jobs:
  etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install -r requirements.txt

      - run: python -m crypto_etl.main
